server.port=9090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6541/ewm-stats}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm}

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health